INSERT INTO `drivers` (`id`, `name`, `surname`, `team`, `nationality`, `image`)
VALUES
('1', 'Lewis', 'Hamilton', 'Mercedes', 'Wielka Brytania', 'img/drivers/Lewis-Hamilton.jpg'),
('2', 'Valtteri', 'Bottas', 'Mercedes', 'Finlandia', 'img/drivers/Valtteri-Bottas.jpg'),
('3', 'Sebastian', 'Vettel', 'Ferrari', 'Niemcy', 'img/drivers/Sebastian-Vettel.jpg'),
('4', 'Max', 'Verstappen', 'Red Bull Racing-Honda', 'Holandia', 'img/drivers/Max-Verstappen.jpg'),
('5', 'Charles', 'Leclerc', 'Ferrari', 'Monako', 'img/drivers/Charles-Leclerc.jpg'),
('6', 'Pierre', 'Gasly', 'Red Bull Racing-Honda', 'Francja', 'img/drivers/Pierre-Gasly.jpg'),
('7', 'Carlos', 'Sainz Jr.', 'McLaren-Renault', 'Finlandia', 'img/drivers/Carlos-Sainz.jpg'),
('8', 'Kevin', 'Magnussen', 'Haas-Ferrari', 'Dania', 'img/drivers/Kevin-Magnussen.jpg'),
('9', 'Sergio', 'Pérez', 'Racing Point-Mercedes', 'Meksyk', 'img/drivers/Sergio-Perez.jpg'),
('10', 'Kimi', 'Räikkönen', 'Alfa Romeo Racing-Ferrari', 'Finlandia', 'img/drivers/Kimi-Raikkonen.jpg'),
('11', 'Lando', 'Norris', 'McLaren-Renault', 'Wielka Brytania', 'img/drivers/Lando-Norris.jpg'),
('12', 'Daniil', 'Kvyat', 'Mercedes', 'Scuderia Toro Rosso-Honda', 'img/drivers/Daniil-Kvyat.jpg'),
('13', 'Daniel', 'Ricciardo', 'Renault', 'Australia', 'img/drivers/Daniel-Ricciardo.jpg'),
('14', 'Alexander', 'Albon', 'Scuderia Toro Rosso-Honda', 'Tajlandia', 'img/drivers/Alexander-Albon.jpg'),
('15', 'Nico', 'Hülkenberg', 'Renault', 'Niemcy', 'img/drivers/Nico-Hulkenberg.jpg'),
('16', 'Lance', 'Stroll', 'Racing Point-BWT Mercedes', 'Kanada', 'img/drivers/Lance-Stroll.jpg'),
('17', 'Romain', 'Grosjean', 'Haas-Ferrari', 'Francja', 'img/drivers/Romain-Grosjean.jpg'),
('18', 'Antonio', 'Giovinazzi', 'Alfa Romeo Racing-Ferrari', 'Włochy', 'img/drivers/Antonio-Giovinazzi.jpg'),
('19', 'George', 'Russell', 'Williams-Mercedes', 'Wielka Brytania', 'img/drivers/George-Russell.jpg'),
('20', 'Robert', 'Kubica', 'Williams-Mercedes', 'Polska', 'img/drivers/Robert-Kubica.jpg');